// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHymX1QZCBGeMoylgxcwMzgrw9Y9B1Qdk',
    appId: '1:779949766964:web:6fdb5b4fdf968d915e8d61',
    messagingSenderId: '779949766964',
    projectId: 'personnal-assistant-3c0c3',
    authDomain: 'personnal-assistant-3c0c3.firebaseapp.com',
    storageBucket: 'personnal-assistant-3c0c3.firebasestorage.app',
    measurementId: 'G-LGPDSC6V2J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQB8BzvsMUJ7pP5GzJ7KdaWVE3vnRKnxE',
    appId: '1:779949766964:android:ef1c61b9575f49f95e8d61',
    messagingSenderId: '779949766964',
    projectId: 'personnal-assistant-3c0c3',
    storageBucket: 'personnal-assistant-3c0c3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHvDiDdicXWNkj8RNS9TRbzpEyRmdzqVk',
    appId: '1:779949766964:ios:ab4ad56289f3ad245e8d61',
    messagingSenderId: '779949766964',
    projectId: 'personnal-assistant-3c0c3',
    storageBucket: 'personnal-assistant-3c0c3.firebasestorage.app',
    androidClientId: '779949766964-g1kjndpc0mg94h0j4s3dn38ei3a50rhk.apps.googleusercontent.com',
    iosClientId: '779949766964-is4a6ntuerg07in3gqg08tqqd11gji9r.apps.googleusercontent.com',
    iosBundleId: 'com.example.assistant',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHvDiDdicXWNkj8RNS9TRbzpEyRmdzqVk',
    appId: '1:779949766964:ios:ab4ad56289f3ad245e8d61',
    messagingSenderId: '779949766964',
    projectId: 'personnal-assistant-3c0c3',
    storageBucket: 'personnal-assistant-3c0c3.firebasestorage.app',
    androidClientId: '779949766964-g1kjndpc0mg94h0j4s3dn38ei3a50rhk.apps.googleusercontent.com',
    iosClientId: '779949766964-is4a6ntuerg07in3gqg08tqqd11gji9r.apps.googleusercontent.com',
    iosBundleId: 'com.example.assistant',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHymX1QZCBGeMoylgxcwMzgrw9Y9B1Qdk',
    appId: '1:779949766964:web:0fecc40c90cd289e5e8d61',
    messagingSenderId: '779949766964',
    projectId: 'personnal-assistant-3c0c3',
    authDomain: 'personnal-assistant-3c0c3.firebaseapp.com',
    storageBucket: 'personnal-assistant-3c0c3.firebasestorage.app',
    measurementId: 'G-QGQ3QE1JZ9',
  );
}
